version: '3.1'
services:
  app:
    build: .
    image: threetrack/myservice
    container_name: myservice
    hostname: myservice
    depends_on:
      - db
      - db2
    ports:
      - "80:8080"
    #  - "8080-8082:8080"
    environment:
      ACTUATOR_UPDATE_SCHEDULED: ${ACTUATOR_UPDATE_SCHEDULED}
      SERVICE_IMPL: ${SERVICE_IMPL}
      REPOSITORY_IMPL: ${REPOSITORY_IMPL}

      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
  db:
    image: "redis:alpine"
    container_name: db
    hostname: db
    ports:
     - "6379:6379"
  db2:
    image: postgres:9.6
    container_name: db2
    hostname: ${POSTGRESQL_HOST}
    #  restart: always
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME}
    volumes:
      - ./db-script:/docker-entrypoint-initdb.d